### PR TITLE
MacOS (and UNIX) support plus installation scripts.

### PR DESCRIPTION
**Pull request by roipeker**
- adds enviroment variables for every Process executed.
- adds build scripts for MacOS (and DMG generation).

Notarized and Signed dmg package can be downloaded [here](https://we.tl/t-QJSq26fadx) (for a week).

### CODE REVIEW

**Comment by damywise** [comment]
I tested it, but the progress ring spins indefinitely.

**Comment by roipeker** [comment]
What Progress ring?

**Comment by damywise** [comment]
When the app first started, there is a progress ring and nothing else

**Comment by roipeker** [comment]
Can u provide details about ur macOs version?

Also please check if you have adb accessible in your OS terminal.

Please paste output of the command (in macos Terminal)

/bin/sh --version

and

/usr/bin/env

**Comment by damywise** [comment]
adb is accessible in terminal

/bin/sh --version:
```
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```
/usr/bin/env:
```
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/m6/59w320h10w14fv0ldrmnx0nh0000gn/T/
XPC_FLAGS=0x0
LaunchInstanceID=6EAB0DAE-1958-43F9-AAB3-736C78FAF415
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.czW6JEecSl/Listeners
SECURITYSESSIONID=186a5
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=C76B9FF5-A15A-4ED3-A6F0-E3E1BE1C1453
SHELL=/bin/zsh
HOME=/Users/XAZ1388
LOGNAME=XAZ1388
USER=XAZ1388
PATH=/Users/XAZ1388/miniconda3/bin:/Users/XAZ1388/miniconda3/condabin:/Users/XAZ1388/miniconda3/condabin:/Applications/XAMPP/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/bin:/Users/XAZ1388/Downloads/flutter/bin
SHLVL=1
PWD=/Users/XAZ1388
OLDPWD=/Users/XAZ1388
HOMEBREW_NO_ANALYTICS=1
DOTNET_CLI_TELEMETRY_OPTOUT=1
POWERSHELL_TELEMETRY_OPTOUT=1
CHROME_EXECUTABLE=/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
CONDA_EXE=/Users/XAZ1388/miniconda3/bin/conda
_CE_M=
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/XAZ1388/miniconda3/bin/python
CONDA_SHLVL=1
CONDA_PREFIX=/Users/XAZ1388/miniconda3
CONDA_DEFAULT_ENV=base
CONDA_PROMPT_MODIFIER=(base) 
LC_CTYPE=UTF-8
_=/usr/bin/env
```

**Comment by roipeker** [comment]
Thanks, everything seems to be correct. 

No idea what could be happening. @IsmailAlamKhan knows where the logs are saved for any exception thrown.

Just to be sure, can you show a screenshot of that spinning thing? Is macOS opening the app? or a Flutter's widget?

**Comment by damywise** [comment]
Probably a widget
image

**Comment by roipeker** [comment]
Yep, indeed. So there must be an exception somewhere. Let's wait for @IsmailAlamKhan to get some ideas, I just limited myself to compile it for macOS, and works for me...

We were waiting for other mac users to check how it works, so thank you so much for the report!

Lets see in a few hours (is bedtime for me) if we can fix it. Please stay reachable for more testings if you can, and thank you for your patience.

**Comment by IsmailAlamKhan** [comment]
@damywise on windows the logs are stored in the appdata folder, so on mac it should be something similar. And thank you so much for testing it.

**Comment by damywise** [comment]
Found it.
It says:
```
Messege: App Started
Messege: Error on zone Error requesting environment: /bin/sh: /Users/XAZ1388/.bashrc: No such file or directory

StackTrace=#0      _loadUnixEnviroment (package:adb_ui/app/features/adb/adb_service.dart:130)
#1      ProccessAdbServiceImpl.run (package:adb_ui/app/features/adb/adb_service.dart:150)
#2      ProccessAdbServiceImpl.verifyAdb (package:adb_ui/app/features/adb/adb_service.dart:451)
#3      App.init (package:adb_ui/app/app.dart:38)
<asynchronous suspension>
#4      App.run.<anonymous closure> (package:adb_ui/app/app.dart:61)
<asynchronous suspension>
```

**Comment by IsmailAlamKhan** [comment]
@damywise thanks a lot for giving the logs, I know little to nothing about Mac 🥲. So let's wait till @roipeker wakes up then we can see what to do about this. Thanks again.

**Comment by roipeker** [comment]
OhMyZeus...😁

The Shell Didn't throw exception on my computer for "source" non-existing env/profile files. Will check for a workaround later today and send a new build.

Thanks for the logs @damywise

**Comment by IsmailAlamKhan** [comment]
@damywise could please try the new build https://we.tl/t-HPZrLWSuqr, thanks.

**Comment by roipeker** [comment]
@damywise, when you are ready, please try again the [latest version (0.0.11)](https://we.tl/t-HPZrLWSuqr) and let us know if it worked.

**Comment by roipeker** [comment]
[New version](https://we.tl/t-rGzWDtbBn9) with custom MacOS Menu, to open Application Support (to check logs just in case).

**Comment by damywise** [comment]
Sorry, I was asleep.
I've tested the new version and it works great now.

**Comment by roipeker** [comment]
Thanks mate.

**Comment by IsmailAlamKhan** [comment]
No worries, thanks a lot @damywise.

**Comment by IsmailAlamKhan** [comment]
@roipeker do you think I should merge the pr now?

**Comment by roipeker** [comment]
It didn't work anyway on macOS before the PR, nothing to lose 😇

**Comment by IsmailAlamKhan** [comment]
Lol fair point 😂😂. I will merge it.

**Pull request merged**
